openapi: 3.0.0
info:
  title: q-cwop
  description: 'Quality-Critical WOrkflow Planner Q-CWOP '
  contact:
    email: S.Koulouzis@uva.nl
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1
servers:
- url: /
paths:
  /cwl:
    post:
      summary: add a cwl workflow
      operationId: add_workflow
      requestBody:
        description: Workflow git request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CWLGit'
            examples:
              example_1:
                value:
                  url: https://bitbucket.org/markrobinson96/workflows.git
                  branch: master
                  path: /workflows/make-to-cwl/dna.cwl
        required: true
      responses:
        "202":
          description: CWLGit Accepted
          content: {}
        "400":
          description: Invalid CWLGit
          content: {}
        "404":
          description: git url not found
          content: {}
        "405":
          description: CWLValidation exception
          content: {}
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /tosca/{cwl_id}:
    get:
      summary: get workflow plan as tosca
      description: Returns a single pet
      operationId: get_tosca_plan
      parameters:
      - name: cwl_id
        in: path
        description: ID of CWLGit
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ToscaTemplate'
        "400":
          description: Invalid ID supplied
          content: {}
        "404":
          description: Pet not found
          content: {}
      x-openapi-router-controller: swagger_server.controllers.default_controller
components:
  schemas:
    CWLGit:
      type: object
      properties:
        id:
          type: string
        url:
          type: string
        branch:
          type: string
        path:
          type: string
    ToscaTemplate:
      type: object

