openapi: 3.0.0
info:
  title: q-cwop
  description: 'Quality-Critical WOrkflow Planner Q-CWOP '
  contact:
    email: S.Koulouzis@uva.nl
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1
servers:
- url: /
paths:
  /cwl:
    post:
      summary: add a cwl workflow
      operationId: addWorkflow
      requestBody:
        description: Workflow git request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CWLGit'
            examples:
              example_1:
                value:
                  url: https://bitbucket.org/markrobinson96/workflows.git
                  branch: master
                  path: /workflows/make-to-cwl/dna.cwl
        required: true
      responses:
        "202":
          description: CWLGit Accepted
          content: {}
        "400":
          description: Invalid CWLGit
          content: {}
        "404":
          description: git url not found
          content: {}
        "405":
          description: CWL  Validation exception
          content: {}
components:
  schemas:
    CWLGit:
      type: object
      properties:
        url:
          type: string
        branch:
          type: string
        path:
          type: string
