openapi: 3.0.0
info:
  title: q-cwop
  description: 'Quality-Critical WOrkflow Planner Q-CWOP '
  contact:
    email: S.Koulouzis@uva.nl
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1
servers:
- url: /
paths:
  /tosca/:
    get:
      summary: get workflow plan as tosca
      description: Returns a single pet
      operationId: getToscaPlan
      parameters:
      - name: git_url
        in: query
        description: cwl git url
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: branch
        in: query
        description: the git branch. default is mater
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: path
        in: query
        description: the git path.
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ToscaTemplate'
        "400":
          description: Invalid url supplied
          content: {}
        "404":
          description: reposetory not found
          content: {}
components:
  schemas:
    ToscaTemplate:
      type: object
