openapi: 3.0.0
info:
  title: q-cwop
  description: 'Quality-Critical WOrkflow Planner Q-CWOP '
  contact:
    email: S.Koulouzis@uva.nl
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1
servers:
- url: /
paths:
  /cwl:
    post:
      summary: add a cwl workflow
      operationId: addWorkflow
      requestBody:
        description: Workflow git request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CWLGit'
        required: true
      responses:
        "400":
          description: Invalid CWLGit
          content: {}
        "404":
          description: git url not found
          content: {}
        "405":
          description: CWL  Validation exception
          content: {}
components:
  schemas:
    CWLGit:
      type: object
      properties:
        id:
          type: integer
          format: int64
        petId:
          type: integer
          format: int64
        quantity:
          type: integer
          format: int32
        shipDate:
          type: string
          format: date-time
        status:
          type: string
          description: Order Status
          enum:
          - placed
          - approved
          - delivered
        complete:
          type: boolean
          default: false
